# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa425a1970827f142b634c38395b267094168ede81dc6081fee057bd384ef031bdfe204f4bbc6518615c61f5336c7d787d76d27771aecebe04c8162e1a1650d6

test:
  secret_key_base: 0335cceb4494d84b369bceb860a8304da2d8bd01beda9322c465f9fef0229b00713db53c9174f1d0518a34eccb98c9c57be193a5469c46251bf41cff3a6ca43d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
